import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

const LEGAL_REPORT_SYSTEM_PROMPT = `
**-- LEGAL REPORT GENERATION PROTOCOL V2.2 --**

**ROLE:** You are an expert Legal Translator and Official Document Generator. Your task is to produce a formal, legally structured complaint/report based on the analysis of hate speech.

**INSTRUCTIONS:**
1. **INPUT VALIDATION:** You will receive the output from the "HSIE-Syria-v2.1" classification (Severity Score, Arabic Reasoning, Violation Type) and the target jurisdiction.
2. **MONOLINGUAL OUTPUT:** The entire final report must be written **EXCLUSIVELY** in the target country's official language (e.g., German for Germany, French for France, Turkish for Turkey, Arabic for Arab countries). DO NOT include any Arabic text in non-Arabic reports.
3. **STRUCTURE:** Generate a formal letter of complaint addressed to the highest relevant legal authority.
4. **NO MARKDOWN:** Do NOT use markdown formatting (no **, no #, no [brackets]). Write clean, formal legal text only.

**REPORT STRUCTURE:**

1. **Formal Address/Salutation** - Address the appropriate authority in formal language
2. **Subject Line** - Clear statement of the complaint
3. **Introduction** - Identify the online content and when it was observed
4. **Legal Analysis** - Translate and integrate the Arabic reasoning, cite the specific legal article provided
5. **Conclusion** - Request immediate investigation and legal action based on severity
6. **Signature** - "This report was automatically generated by the Violence and Hate Speech Observatory" (translated)

**CRITICAL:** Output ONLY the formal letter text. No section headers, no markdown, no explanations.

**DELIVERABLE:** The complete legal report as clean, formal text ready for submission.
`;

export async function POST(req: NextRequest) {
    try {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: 'GEMINI_API_KEY is not set' }, { status: 500 });
        }

        const { jurisdiction, text, reasoning_ar, severity_score, legal_citation } = await req.json();

        if (!jurisdiction || !text || !reasoning_ar || !legal_citation) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

        const prompt = `
**DATA INPUT:**
* **TARGET JURISDICTION:** ${jurisdiction}
* **ORIGINAL HATE SPEECH TEXT:** ${text}
* **ARABIC REASONING:** ${reasoning_ar}
* **SEVERITY SCORE:** ${severity_score}
* **LEGAL CITATION:** ${legal_citation}
`;

        const result = await model.generateContent([LEGAL_REPORT_SYSTEM_PROMPT, prompt]);
        const report = result.response.text();

        return NextResponse.json({ report });
    } catch (error: any) {
        console.error('Error generating report:', error);
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
    }
}
